import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4'
import { sendPushNotification } from 'npm:@mmmike/web-push@0.1.0/send'

const url=Deno.env.get('SUPABASE_URL')
const serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')
const db=createClient(url,serviceKey,{auth:{persistSession:false}})
const enc=new TextEncoder()
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8'}
const EMOJIS=['❤️','🔥','😂','👏','💪','⚡']
const METRICS=['points','activities','knowledge','active_days','custom']
const AVATAR={presentation:['neutral','masculine','feminine'],body:['regular','slim','broad'],tone:['warm','light','medium','deep'],hair:['wave','short','curl','buzz','long','messy','fade','undercut'],hairColor:['darkbrown','black','brown','blonde','darkblonde','red','grey','white','blue','purple','pink','green'],outfit:['tee','hoodie','sport','jacket','sweater','tank','premium'],accessory:['none','glasses','sunglasses','earring','necklace','headphones','sport','cap','headband','crown'],head:['none','cap','beanie','crown'],effect:['none','glow','spark','battle'],background:['mint','sky','lilac','sun','rose','night','battle']}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:cors})}
function safeText(v,max=300){return typeof v==='string'?v.trim().slice(0,max):''}
async function hashText(v){const d=await crypto.subtle.digest('SHA-256',enc.encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function current(token){if(!token||token.length<24)return null;const h=await hashText(token);const {data}=await db.from('me_profiles').select('*').eq('device_token_hash',h).maybeSingle();return data||null}
function rank(points){const names=['Starter','Beginner','Groeier','Professional','Baas','Elite','Expert','Meester','Legende','Topper','Me+ Legende'];const level=Math.min(11,Math.floor(Math.max(0,Number(points)||0)/10)+1);return {level,rank:names[level-1]}}
function avatarConfig(v={}){const out={};for(const k of Object.keys(AVATAR)){const x=safeText(v?.[k],20);out[k]=AVATAR[k].includes(x)?x:AVATAR[k][0]}return out}
function profileOut(p,full=true){if(!p)return null;const last=p.last_seen_at?new Date(p.last_seen_at):null;const online=!!last&&(Date.now()-last.getTime()<120000);const r=rank(p.points||0);return {id:p.id,name:p.display_name,handle:p.handle,avatarSeed:p.avatar_seed,avatarConfig:avatarConfig(p.avatar_config||{}),accentTheme:p.accent_theme||'fresh',points:full?Number(p.points||0):null,xp:full?Number(p.xp||0):null,level:full?r.level:null,rank:full?r.rank:null,lastSeenAt:p.last_seen_at,online}}
async function relationships(userId){const {data,error}=await db.from('me_follows').select('follower_id,following_id,status').or(`follower_id.eq.${userId},following_id.eq.${userId}`);if(error)throw error;return data||[]}
async function friendIds(userId){const r=await relationships(userId);return r.filter(x=>x.status==='accepted').map(x=>x.follower_id===userId?x.following_id:x.follower_id)}
async function acceptedBetween(a,b){const {data}=await db.from('me_follows').select('follower_id').eq('status','accepted').or(`and(follower_id.eq.${a},following_id.eq.${b}),and(follower_id.eq.${b},following_id.eq.${a})`).limit(1);return !!data?.length}
async function configValue(key){const {data}=await db.from('me_server_config').select('value').eq('key',key).maybeSingle();return data?.value||''}
async function attentionCount(userId){const [{count:requests},{count:messages},{count:battles}]=await Promise.all([db.from('me_follows').select('*',{count:'exact',head:true}).eq('following_id',userId).eq('status','pending'),db.from('me_messages').select('*',{count:'exact',head:true}).eq('recipient_id',userId).is('read_at',null),db.from('me_battles').select('*',{count:'exact',head:true}).eq('opponent_id',userId).eq('status','pending')]);return (requests||0)+(messages||0)+(battles||0)}
async function notifyAndPush(userId,actorId,type,body,data={}){await db.from('me_notifications').insert({user_id:userId,actor_id:actorId,type,body,data});const {data:p}=await db.from('me_profiles').select('notifications_enabled').eq('id',userId).maybeSingle();if(!p?.notifications_enabled)return;const {data:subs}=await db.from('me_push_subscriptions').select('id,endpoint,p256dh,auth').eq('user_id',userId).eq('active',true).order('updated_at',{ascending:false}).limit(1);if(!subs?.length)return;const publicKey=await configValue('vapid_public'),privateKey=await configValue('vapid_private');if(!publicKey||!privateKey)return;const deliveryKey=crypto.randomUUID();const badgeCount=await attentionCount(userId);for(const s of subs){try{await sendPushNotification({endpoint:s.endpoint,keys:{p256dh:s.p256dh,auth:s.auth}},{title:'me+',body,tag:`me-social-${type}-${deliveryKey.slice(0,12)}`,data:{url:'./',badgeCount,deliveryKey,type,...data}},{publicKey,privateKey,subject:'https://steenoventijn-bot.github.io/me-plus/'})}catch(e){const code=Number(e?.statusCode||e?.status||0);if(code===404||code===410)await db.from('me_push_subscriptions').update({active:false,updated_at:new Date().toISOString()}).eq('id',s.id)}}}
function decodeImage(dataUrl){const m=dataUrl.match(/^data:(image\/(?:jpeg|png|webp));base64,(.+)$/);if(!m)throw new Error('Gebruik een JPG, PNG of WebP-foto.');const bytes=Uint8Array.from(atob(m[2]),c=>c.charCodeAt(0));if(bytes.length>6*1024*1024)throw new Error('Foto is groter dan 6 MB.');return {bytes,mime:m[1],ext:m[1]==='image/png'?'png':m[1]==='image/webp'?'webp':'jpg'}}
async function battleScore(b,userId){if(!b.starts_at)return 0;const start=b.starts_at,end=new Date(Math.min(Date.now(),b.ends_at?new Date(b.ends_at).getTime():Date.now())).toISOString();if(b.metric==='custom'){const {count}=await db.from('me_battle_checkins').select('*',{count:'exact',head:true}).eq('battle_id',b.id).eq('user_id',userId).gte('created_at',start).lte('created_at',end);return count||0}const {data,error}=await db.from('me_point_events').select('points,kind,local_date').eq('user_id',userId).gte('created_at',start).lte('created_at',end);if(error)throw error;const rows=data||[];if(b.metric==='points')return rows.reduce((n,x)=>n+Number(x.points||0),0);if(b.metric==='activities')return rows.filter(x=>x.kind==='activity').length;if(b.metric==='knowledge')return rows.filter(x=>x.kind==='knowledge').length;if(b.metric==='active_days')return new Set(rows.map(x=>x.local_date).filter(Boolean)).size;return 0}
async function finalizeBattle(b){if(b.status!=='active'||!b.ends_at||new Date(b.ends_at).getTime()>Date.now())return b;const [a,c]=await Promise.all([battleScore(b,b.challenger_id),battleScore(b,b.opponent_id)]);const winner=a===c?null:a>c?b.challenger_id:b.opponent_id;const now=new Date().toISOString();const {data:updated}=await db.from('me_battles').update({status:'completed',completed_at:now,winner_id:winner,rewarded_at:now}).eq('id',b.id).eq('status','active').select('*').maybeSingle();if(updated&&winner){const {data:p}=await db.from('me_profiles').select('xp').eq('id',winner).single();await db.from('me_profiles').update({xp:Number(p?.xp||0)+50}).eq('id',winner);const loser=winner===b.challenger_id?b.opponent_id:b.challenger_id;await Promise.all([notifyAndPush(winner,null,'battle_win','🏆 Je hebt een battle gewonnen! +50 XP',{battleId:b.id}),notifyAndPush(loser,null,'battle_end','Je battle is afgelopen. Tijd voor de uitslag.',{battleId:b.id})]);return updated}return updated||b}
async function battleProfiles(b){const {data}=await db.from('me_profiles').select('*').in('id',[b.challenger_id,b.opponent_id]);const map=new Map((data||[]).map(p=>[p.id,p]));return {challenger:profileOut(map.get(b.challenger_id)),opponent:profileOut(map.get(b.opponent_id))}}
function metricLabel(m){return ({points:'Meeste punten',activities:'Meeste activiteiten',knowledge:'Meeste kennis',active_days:'Meeste dagen actief',custom:'Custom Battle'})[m]||m}
async function battleDetail(b,meId){b=await finalizeBattle(b);const [profiles,challengerScore,opponentScore]=await Promise.all([battleProfiles(b),battleScore(b,b.challenger_id),battleScore(b,b.opponent_id)]);let recent=[];if(b.starts_at){const {data:ev}=await db.from('me_point_events').select('id,user_id,title,kind,points,created_at').in('user_id',[b.challenger_id,b.opponent_id]).gte('created_at',b.starts_at).order('created_at',{ascending:false}).limit(16);recent=(ev||[]).map(x=>({...x,name:x.user_id===b.challenger_id?profiles.challenger?.name:profiles.opponent?.name}))}if(b.metric==='custom'){const {data:ci}=await db.from('me_battle_checkins').select('id,user_id,note,created_at').eq('battle_id',b.id).order('created_at',{ascending:false}).limit(16);recent=(ci||[]).map(x=>({id:x.id,user_id:x.user_id,title:x.note||b.custom_label||'Custom check-in',kind:'custom',points:1,created_at:x.created_at,name:x.user_id===b.challenger_id?profiles.challenger?.name:profiles.opponent?.name}))}return {battle:{...b,metricLabel:metricLabel(b.metric),challengerScore,opponentScore,isMine:b.challenger_id===meId},profiles,recent}}
async function accessibleBattle(id,meId){const {data}=await db.from('me_battles').select('*').eq('id',id).maybeSingle();if(!data||(data.challenger_id!==meId&&data.opponent_id!==meId))return null;return data}
async function messageRows(meId,other){const {data,error}=await db.from('me_messages').select('id,sender_id,recipient_id,body,created_at,read_at,message_type,media_path,media_mime,reply_to_id,battle_id').or(`and(sender_id.eq.${meId},recipient_id.eq.${other}),and(sender_id.eq.${other},recipient_id.eq.${meId})`).order('created_at',{ascending:true}).limit(250);if(error)throw error;return data||[]}
async function enrichMessages(rows){const ids=rows.map(x=>x.id);const {data:rs}=ids.length?await db.from('me_message_reactions').select('message_id,user_id,emoji').in('message_id',ids):{data:[]};const reactions=new Map();for(const r of rs||[]){if(!reactions.has(r.message_id))reactions.set(r.message_id,[]);reactions.get(r.message_id).push({userId:r.user_id,emoji:r.emoji})}const out=[];for(const m of rows){let mediaUrl=null;if(m.media_path){const {data:s}=await db.storage.from('me-chat').createSignedUrl(m.media_path,600);mediaUrl=s?.signedUrl||null}out.push({...m,mediaUrl,reactions:reactions.get(m.id)||[]})}return out}
async function friendProfile(me,otherId){if(!await acceptedBetween(me.id,otherId))return null;const {data:p}=await db.from('me_profiles').select('*').eq('id',otherId).maybeSingle();if(!p)return null;const [{count:activities},{count:reads},{data:battles}]=await Promise.all([db.from('me_point_events').select('*',{count:'exact',head:true}).eq('user_id',otherId).eq('kind','activity'),db.from('me_knowledge_reads').select('*',{count:'exact',head:true}).eq('user_id',otherId),db.from('me_battles').select('id,status,winner_id,challenger_id,opponent_id').or(`challenger_id.eq.${otherId},opponent_id.eq.${otherId}`)]);const together=(battles||[]).filter(b=>(b.challenger_id===me.id&&b.opponent_id===otherId)||(b.challenger_id===otherId&&b.opponent_id===me.id));const wins=(battles||[]).filter(b=>b.winner_id===otherId).length;const togetherWins=together.filter(b=>b.winner_id===otherId).length;const points=Number(p.points||0),xp=Number(p.xp||0);const badges=[activities>=25?'💪 Consistent':null,reads>=10?'📚 Knowledge':null,wins>=3?'⚔️ Battle Beast':null,points>=100?'🏆 Century':null,xp>=250?'✨ XP Hunter':null].filter(Boolean);return {profile:profileOut(p),stats:{activities:activities||0,knowledge:reads||0,battles:(battles||[]).length,wins,together:together.length,togetherWins},badges}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);let body={};try{body=await req.json()}catch{return json({error:'Ongeldige aanvraag'},400)}const token=safeText(body.token,220),op=safeText(body.op,50);const me=await current(token);if(!me)return json({error:'Profiel niet gevonden'},401);await db.from('me_profiles').update({last_seen_at:new Date().toISOString()}).eq('id',me.id);try{
if(op==='game_profile')return json({profile:profileOut(me)});
if(op==='avatar_settings'){const patch={};if(body.avatarConfig)patch.avatar_config=avatarConfig({...me.avatar_config,...body.avatarConfig});if(['fresh','ocean','dream','energy','pink'].includes(body.accentTheme))patch.accent_theme=body.accentTheme;const {data,error}=await db.from('me_profiles').update(patch).eq('id',me.id).select('*').single();if(error)throw error;return json({profile:profileOut(data)})}
if(op==='friend_profile'){const p=await friendProfile(me,safeText(body.userId,60));if(!p)return json({error:'Vriend niet gevonden'},404);return json(p)}
if(op==='battle_create'){const other=safeText(body.userId,60),metric=METRICS.includes(body.metric)?body.metric:'points',duration=Math.max(1,Math.min(744,Number(body.durationHours)||168));if(!other||!await acceptedBetween(me.id,other))return json({error:'Je kunt alleen vrienden uitdagen.'},403);const customLabel=metric==='custom'?safeText(body.customLabel,80):null,customTarget=metric==='custom'?Math.max(1,Math.min(500,Number(body.customTarget)||5)):null;if(metric==='custom'&&!customLabel)return json({error:'Geef je custom battle een doel.'},400);const {data:b,error}=await db.from('me_battles').insert({challenger_id:me.id,opponent_id:other,metric,custom_label:customLabel,custom_target:customTarget,duration_hours:duration,status:'pending',rematch_of:body.rematchOf||null}).select('*').single();if(error)throw error;await db.from('me_messages').insert({sender_id:me.id,recipient_id:other,body:`⚔️ ${me.display_name} daagt je uit: ${metricLabel(metric)}`,message_type:'battle',battle_id:b.id});await notifyAndPush(other,me.id,'battle_invite',`⚔️ ${me.display_name} daagt je uit! ${duration>=24?Math.round(duration/24)+' dagen':duration+' uur'} · ${metricLabel(metric)}.`,{battleId:b.id});return json(await battleDetail(b,me.id))}
if(op==='battle_respond'){const id=safeText(body.battleId,60),action=safeText(body.action,12);const b=await accessibleBattle(id,me.id);if(!b||b.opponent_id!==me.id||b.status!=='pending')return json({error:'Battle-uitdaging niet gevonden.'},404);if(action==='decline'){const {data:u}=await db.from('me_battles').update({status:'declined'}).eq('id',id).eq('status','pending').select('*').single();await db.from('me_messages').insert({sender_id:me.id,recipient_id:b.challenger_id,body:'Battle geweigerd',message_type:'battle',battle_id:id});await notifyAndPush(b.challenger_id,me.id,'battle_declined',`${me.display_name} heeft je battle-uitdaging geweigerd.`,{battleId:id});return json({battle:u})}if(action!=='accept')return json({error:'Ongeldige keuze'},400);const now=new Date(),ends=new Date(now.getTime()+b.duration_hours*3600000);const {data:u,error}=await db.from('me_battles').update({status:'active',accepted_at:now.toISOString(),starts_at:now.toISOString(),ends_at:ends.toISOString()}).eq('id',id).eq('status','pending').select('*').single();if(error)throw error;await db.from('me_messages').insert({sender_id:me.id,recipient_id:b.challenger_id,body:'⚔️ Battle gestart',message_type:'battle',battle_id:id});await notifyAndPush(b.challenger_id,me.id,'battle_start',`⚔️ ${me.display_name} heeft geaccepteerd. Battle ready!`,{battleId:id});return json(await battleDetail(u,me.id))}
if(op==='battle_list'){const {data}=await db.from('me_battles').select('*').or(`challenger_id.eq.${me.id},opponent_id.eq.${me.id}`).order('created_at',{ascending:false}).limit(80);const rows=[];for(let b of data||[]){b=await finalizeBattle(b);rows.push({...b,profiles:await battleProfiles(b)})}return json({incoming:rows.filter(b=>b.status==='pending'&&b.opponent_id===me.id),outgoing:rows.filter(b=>b.status==='pending'&&b.challenger_id===me.id),active:rows.filter(b=>b.status==='active'),recent:rows.filter(b=>['completed','declined','cancelled'].includes(b.status)).slice(0,12)})}
if(op==='battle_detail'){const b=await accessibleBattle(safeText(body.battleId,60),me.id);if(!b)return json({error:'Battle niet gevonden'},404);return json(await battleDetail(b,me.id))}
if(op==='battle_checkin'){const b=await accessibleBattle(safeText(body.battleId,60),me.id);if(!b||b.status!=='active'||b.metric!=='custom')return json({error:'Custom battle is niet actief.'},409);if(b.ends_at&&new Date(b.ends_at).getTime()<=Date.now())return json(await battleDetail(await finalizeBattle(b),me.id));const since=new Date(Date.now()-8000).toISOString();const {count}=await db.from('me_battle_checkins').select('*',{count:'exact',head:true}).eq('battle_id',b.id).eq('user_id',me.id).gte('created_at',since);if(count)return json({error:'Wacht even voordat je opnieuw scoort.'},429);await db.from('me_battle_checkins').insert({battle_id:b.id,user_id:me.id,note:safeText(body.note,120)||b.custom_label});return json(await battleDetail(b,me.id))}
if(op==='battle_rematch'){const old=await accessibleBattle(safeText(body.battleId,60),me.id);if(!old||!['completed','declined','cancelled'].includes(old.status))return json({error:'Deze battle kan nog niet opnieuw.'},409);const other=old.challenger_id===me.id?old.opponent_id:old.challenger_id;const {data:b,error}=await db.from('me_battles').insert({challenger_id:me.id,opponent_id:other,metric:old.metric,custom_label:old.custom_label,custom_target:old.custom_target,duration_hours:old.duration_hours,status:'pending',rematch_of:old.id}).select('*').single();if(error)throw error;await db.from('me_messages').insert({sender_id:me.id,recipient_id:other,body:'⚔️ Rematch-uitdaging',message_type:'battle',battle_id:b.id});await notifyAndPush(other,me.id,'battle_invite',`⚔️ ${me.display_name} wil een rematch!`,{battleId:b.id});return json(await battleDetail(b,me.id))}
if(op==='friend_leaderboard'){const period=['week','month','all'].includes(body.period)?body.period:'week',ids=[me.id,...await friendIds(me.id)];const {data:ps}=await db.from('me_profiles').select('*').in('id',ids);const visible=(ps||[]).filter(p=>p.id===me.id||p.share_progress);let since=null;const n=new Date();if(period==='week'){const d=new Date(n);d.setDate(n.getDate()-6);d.setHours(0,0,0,0);since=d.toISOString()}if(period==='month'){const d=new Date(n.getFullYear(),n.getMonth(),1);since=d.toISOString()}const scores=new Map();if(period==='all'){for(const p of visible)scores.set(p.id,Number(p.points||0))}else{let q=db.from('me_point_events').select('user_id,points').in('user_id',visible.map(p=>p.id));if(since)q=q.gte('created_at',since);const {data:ev}=await q;for(const e of ev||[])scores.set(e.user_id,(scores.get(e.user_id)||0)+Number(e.points||0))}return json({period,rows:visible.map(p=>({...profileOut(p),score:scores.get(p.id)||0,isMe:p.id===me.id})).sort((a,b)=>b.score-a.score)})}
if(op==='messages_v10'){const other=safeText(body.userId,60);if(!await acceptedBetween(me.id,other))return json({error:'Jullie moeten eerst vrienden zijn.'},403);const rows=await messageRows(me.id,other);await db.from('me_messages').update({read_at:new Date().toISOString()}).eq('recipient_id',me.id).eq('sender_id',other).is('read_at',null);const {data:p}=await db.from('me_profiles').select('*').eq('id',other).single();return json({friend:profileOut(p),messages:await enrichMessages(rows)})}
if(op==='send_message_v10'){const other=safeText(body.userId,60);if(!await acceptedBetween(me.id,other))return json({error:'Jullie moeten eerst vrienden zijn.'},403);let text=safeText(body.text,1200),messageType='text',mediaPath=null,mediaMime=null;if(body.dataUrl){const img=decodeImage(safeText(body.dataUrl,9000000)),path=`${me.id}/${other}/${crypto.randomUUID()}.${img.ext}`;const {error:up}=await db.storage.from('me-chat').upload(path,img.bytes,{contentType:img.mime,upsert:false});if(up)throw up;mediaPath=path;mediaMime=img.mime;messageType='photo';if(!text)text='Foto'}if(!text)return json({error:'Bericht is leeg'},400);let replyToId=null;const candidate=safeText(body.replyToId,60);if(candidate){const {data:r}=await db.from('me_messages').select('id,sender_id,recipient_id').eq('id',candidate).maybeSingle();if(r&&[r.sender_id,r.recipient_id].includes(me.id)&&[r.sender_id,r.recipient_id].includes(other))replyToId=r.id}const {data:m,error}=await db.from('me_messages').insert({sender_id:me.id,recipient_id:other,body:text,message_type:messageType,media_path:mediaPath,media_mime:mediaMime,reply_to_id:replyToId}).select('*').single();if(error)throw error;await notifyAndPush(other,me.id,'message',messageType==='photo'?`${me.display_name} stuurde een foto.`:`${me.display_name}: ${text.slice(0,80)}`,{userId:me.id});const [enriched]=await enrichMessages([m]);return json({message:enriched})}
if(op==='react_message'){const id=safeText(body.messageId,60),emoji=EMOJIS.includes(body.emoji)?body.emoji:'';if(!emoji)return json({error:'Reactie niet ondersteund'},400);const {data:m}=await db.from('me_messages').select('sender_id,recipient_id').eq('id',id).maybeSingle();if(!m||![m.sender_id,m.recipient_id].includes(me.id))return json({error:'Bericht niet gevonden'},404);const {data:old}=await db.from('me_message_reactions').select('emoji').eq('message_id',id).eq('user_id',me.id).maybeSingle();if(old?.emoji===emoji)await db.from('me_message_reactions').delete().eq('message_id',id).eq('user_id',me.id);else await db.from('me_message_reactions').upsert({message_id:id,user_id:me.id,emoji},{onConflict:'message_id,user_id'});const {data:rs}=await db.from('me_message_reactions').select('user_id,emoji').eq('message_id',id);return json({reactions:(rs||[]).map(r=>({userId:r.user_id,emoji:r.emoji}))})}
return json({error:'Onbekende actie'},400)}catch(e){console.error(e);return json({error:e?.message||'Er ging iets mis. Probeer opnieuw.'},500)}})
