import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {stripTypeScriptTypes} from 'node:module';import {canSeePhoto} from '../supabase/functions/me-plus-api/photo-policy.ts';
function database(tables){const signed=[];return {signed,from(name){let filters=[],patch,single=false,start=0,end=Infinity;const field=(r,k)=>k.includes('->>')?r[k.split('->>')[0]]?.[k.split('->>')[1]]:r[k];const q={select(){return q},eq(k,v){filters.push(r=>field(r,k)===v);return q},in(k,v){filters.push(r=>v.includes(field(r,k)));return q},not(k,op,v){filters.push(r=>field(r,k)!==v);return q},gte(k,v){filters.push(r=>field(r,k)>=v);return q},lt(k,v){filters.push(r=>field(r,k)<v);return q},or(){return q},order(){return q},range(a,b){start=a;end=b+1;return q},limit(n){end=n;return q},update(p){patch=p;return q},maybeSingle(){single=true;return q},then(resolve,reject){try{const rows=(tables[name]||[]).filter(r=>filters.every(f=>f(r))).slice(start,end);if(patch)for(const row of rows)Object.assign(row,structuredClone(patch));return Promise.resolve({data:structuredClone(single?rows[0]||null:rows),error:null}).then(resolve,reject)}catch(e){return Promise.reject(e).then(resolve,reject)}}};return q},storage:{from(){return {async createSignedUrls(paths){signed.push(...paths);return {data:paths.map(path=>({path,signedUrl:'signed:'+path})),error:null}}}}}}}
function setup(){const tables={me_notifications:[{id:'note',actor_id:'author',user_id:'viewer',type:'activity',created_at:new Date().toISOString(),data:{eventId:'photo',pushStatus:'pending'}}],me_profiles:[{id:'author',display_name:'Friend',share_tasks:true,share_proof:true},{id:'viewer',notifications_enabled:true}],me_follows:[{follower_id:'author',following_id:'viewer',status:'accepted'}],me_point_events:[{id:'photo',user_id:'author',kind:'activity',proof_path:'author/photo.jpg',title:'Walk'}],me_push_subscriptions:['phone','tablet'].map(id=>({id,user_id:'viewer',active:true,endpoint:id}))};return {tables,db:database(tables)}}
test('photo push reaches both devices, retries only the failed device, and links to the exact photo',async()=>{const {tables,db}=setup(),calls=[];let fail=true;const source=fs.readFileSync('supabase/functions/me-plus-push-worker/index.ts','utf8'),chunk=source.slice(source.indexOf('async function sendActivityPhotos'),source.indexOf('Deno.serve'));
 const ctx={db,Date,encodeURIComponent,console,configValue:async()=> 'test',sendPushNotification:async(sub,payload)=>{calls.push([sub.endpoint,payload]);if(sub.endpoint==='tablet'&&fail)throw Error('temporary');return true}};vm.createContext(ctx);vm.runInContext(stripTypeScriptTypes(chunk)+';this.run=sendActivityPhotos',ctx);
 await ctx.run('photo');assert.equal(tables.me_notifications[0].data.pushStatus,'pending');fail=false;await ctx.run('photo');assert.equal(tables.me_notifications[0].data.pushStatus,'sent');await ctx.run('photo');assert.deepEqual(calls.map(x=>x[0]),['phone','tablet','tablet']);assert.ok(calls.every(x=>x[1].data.url.endsWith('&photo=photo')));
 tables.me_notifications[0].data={eventId:'photo',pushStatus:'pending'};tables.me_profiles[0].share_proof=false;await ctx.run('photo');assert.equal(calls.length,3);assert.equal(tables.me_notifications[0].data.pushStatus,'skipped');
});
test('gallery signs only the requested visible photo; private and non-friend albums stay inaccessible',async()=>{const {tables,db}=setup();tables.me_point_events.push({id:'private',user_id:'private-author',kind:'activity',proof_path:'secret.jpg'});tables.me_profiles.push({id:'private-author',share_tasks:false,share_proof:false});const source=fs.readFileSync('supabase/functions/me-plus-api/index.ts','utf8'),chunk=source.slice(source.indexOf("    if(op==='photo_gallery')"),source.indexOf("    if (op === 'feed')"));const ctx={db,me:{id:'viewer'},body:{scope:'friends',userId:'author',photoId:'photo'},op:'photo_gallery',safeText:(v)=>v||'',canSeePhoto,acceptedFriendIds:async()=>['author','private-author'],json:(body,status=200)=>({body,status})};vm.createContext(ctx);vm.runInContext(stripTypeScriptTypes('async function run(){'+chunk+'};this.run=run'),ctx);
 let r=await ctx.run();assert.equal(r.body.items[0].url,'signed:author/photo.jpg');assert.deepEqual(db.signed,['author/photo.jpg']);ctx.body.userId='stranger';r=await ctx.run();assert.equal(r.status,403);ctx.body.userId='private-author';ctx.body.photoId='private';r=await ctx.run();assert.equal(r.body.items.length,0);assert.deepEqual(db.signed,['author/photo.jpg']);
});
