import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {webcrypto} from 'node:crypto';
export function runtime(){
 const loader=fs.readFileSync('app.js','utf8'),paths=[...loader.matchAll(/'\.\/(parts\/[^']+)'/g)].map(m=>m[1]),read=p=>fs.readFileSync(p,'utf8');let base=paths.slice(0,5).map(read).join('');const extras=paths.slice(5).map(read).join('\n'),cut=base.lastIndexOf("document.addEventListener('visibilitychange'");
 const exposed=`window.testApp={load:(id)=>mwLoad(id,true),home:()=>q6ReturnOwnWorld(),refresh:()=>refreshBase(),apply:p=>v13q4ApplyProfile(p),get:()=>({profile:server.profile,me:server.v10.me,world:mw.data?.owner?.id,owner:mw.ownerId,viewed:mw.viewedWorldId}),setup:mock=>{server.profile={id:'own',name:'Test',points:0};server.v10.me=server.profile;mw.data=null;view='world';render=()=>{};mwStartHeartbeat=()=>{};call=mock;},avatar:v10Avatar,seconds:k14Seconds};return;`;
 const context={console,URL,URLSearchParams,TextEncoder,Uint8Array,Date,Map,Set,Promise,performance,crypto:webcrypto,structuredClone,localStorage:{getItem:()=>null,setItem(){},removeItem(){}},navigator:{hardwareConcurrency:4,deviceMemory:4,userAgent:'test'},document:{documentElement:{style:{setProperty(){}},dataset:{},classList:{add(){}}},addEventListener(){},removeEventListener(){},querySelector:()=>null,querySelectorAll:()=>[],getElementById:()=>null},matchMedia:()=>({matches:false,addEventListener(){}}),addEventListener(){},setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},requestAnimationFrame:()=>1,cancelAnimationFrame(){},fetch:()=>{throw Error('Network forbidden in test')}};context.window=context;vm.createContext(context);vm.runInContext(base.slice(0,cut)+extras+'\n'+exposed+base.slice(cut),context,{timeout:5000});return context.testApp;
}
const avatar={presentation:'feminine',body:'slim',tone:'deep',hair:'undercut',hairColor:'purple',outfit:'premium',accessory:'headphones',head:'beanie',effect:'glow',background:'night'};
test('complete loader evaluates and preserves all avatar fields across refresh',async()=>{const a=runtime(),calls=[];a.setup(async(base,op)=>{calls.push(op);return op==='me'?{profile:{id:'own',avatarConfig:avatar}}:{}});await a.refresh();assert.equal(calls.includes('game_profile'),false);assert.deepEqual(JSON.parse(JSON.stringify(a.get().profile.avatarConfig)),avatar);assert.equal(a.get().profile,a.get().me)});
test('partial profile responses do not erase saved avatar fields',()=>{const a=runtime();a.setup(()=>{});a.apply({id:'own',avatarConfig:avatar});a.apply({id:'own',name:'Updated',avatarConfig:{tone:'light'}});assert.equal(a.get().profile.avatarConfig.hairColor,'purple');assert.equal(a.get().profile.avatarConfig.tone,'light');a.apply({id:'friend',avatarConfig:{hairColor:'red'}});assert.equal(a.get().profile.id,'own');assert.equal(a.get().profile.avatarConfig.hairColor,'purple')});
test('a slow friend response cannot replace own world after leaving',async()=>{const a=runtime();let resolveFriend;const payload=id=>({owner:{id},isOwner:id==='own',world:{coins:0,house:{}},items:[]});a.setup(async(base,op,data)=>data.userId==='friend'?new Promise(r=>resolveFriend=r):payload('own'));const old=a.load('friend');await a.home();resolveFriend(payload('friend'));await old;assert.equal(a.get().world,'own');assert.equal(a.get().owner,'own');assert.equal(a.get().viewed,'own')});
test('a later friend selection wins over an earlier visit',async()=>{const a=runtime();let first;a.setup(async(base,op,d)=>d.userId==='first'?new Promise(r=>first=r):{owner:{id:d.userId},world:{}});const pending=a.load('first');await a.load('second');first({owner:{id:'first'},world:{}});await pending;assert.equal(a.get().world,'second')});
test('all eight hairstyles preserve the complete rendering layer order',()=>{const a=runtime();a.setup(()=>{});const layers=['background','back-hair','body','clothing','head-skin','face','front-hair','accessories','head-items','effects'];for(const hair of ['wave','short','curl','buzz','long','messy','fade','undercut']){const svg=a.avatar({avatarConfig:{...avatar,hair}},'xl');let previous=-1;for(const layer of layers){const pos=svg.indexOf(`data-layer="${layer}"`);assert.ok(pos>previous,`${hair}: ${layer}`);previous=pos}assert.equal(svg.includes('undefined'),false)}});
