begin;
alter table public.me_read_sessions drop constraint me_read_sessions_min_seconds_check;
alter table public.me_read_sessions add constraint me_read_sessions_min_seconds_check check(min_seconds>=1);
update public.me_knowledge_articles set title='Bomen en schimmels helpen elkaar',intro='Onder de grond werken boomwortels samen met schimmels.',body='Schimmels groeien met dunne draden door de grond. Daarmee bereiken ze water en voedingsstoffen waar wortels moeilijk bij kunnen. De boom krijgt daar een deel van. In ruil geeft de boom suikers aan de schimmel. Die maakt de boom met behulp van zonlicht. Dat heet fotosynthese.

Soms verbindt een schimmel meerdere planten. Via die verbindingen kunnen stoffen bewegen. Maar dat betekent niet dat bomen altijd bewust voor elkaar zorgen. Planten en schimmels kunnen ook om voedsel strijden. Onderzoekers zoeken nog uit hoe dit in een echt bos werkt.',extra_fact='Deze wortelschimmels heten mycorrhizaschimmels. Veel planten werken met zulke schimmels samen.',why_it_matters='Een bos bestaat uit meer dan bomen. Ook het leven onder de grond telt mee.' where slug='bomen-netwerk';
update public.me_knowledge_articles set title='Waarom steden vaak aan een rivier liggen',intro='Water was vroeger een handige weg voor mensen en spullen.',body='Over een rivier konden boten veel graan, hout en steen tegelijk meenemen. Over slechte wegen was dat veel lastiger. Bij kruispunten van routes kwamen handelaren samen. Daar ontstonden markten, werkplaatsen en plekken om spullen op te slaan.

Meer handel trok meer mensen aan. Zo kon een kleine plaats uitgroeien tot een stad. Toch bleef succes niet vanzelf bestaan. Een overstroming, oorlog of nieuwe handelsroute kon alles veranderen.',extra_fact='Oude bruggen en marktpleinen laten soms nog zien hoe een stad is ontstaan.',why_it_matters='Goede verbindingen helpen een stad groeien. De keuzes van mensen bepalen wat er daarna gebeurt.' where slug='cities-and-trade';
update public.me_knowledge_articles set title='Wie bepaalt hoe laat het is?',intro='Tijdzones zijn afspraken tussen mensen.',body='Vroeger keek een plaats vaak naar de stand van de zon om de tijd te bepalen. Daardoor kon het in de volgende stad net een andere tijd zijn. Dat werd lastig toen treinen tussen steeds meer plaatsen reden.

Met vaste tijdzones konden mensen treinreizen en berichten beter op elkaar afstemmen. De grenzen volgen daarom niet alleen de zon. Landen houden ook rekening met handel en het dagelijks leven.',extra_fact='Sommige grote landen gebruiken één officiële tijd. Andere hebben meerdere tijdzones.',why_it_matters='De klok lijkt vanzelfsprekend, maar er zitten veel afspraken achter.' where slug='culturele-tijdzones';
update public.me_knowledge_articles set title='Je geheugen is geen filmpje',intro='Je brein bouwt een herinnering telkens opnieuw op.',body='Als je terugdenkt aan een gebeurtenis, haalt je brein losse stukjes bij elkaar. Denk aan beelden, geluiden en gevoelens. Ook wat je later hoort, kan invloed hebben op wat je denkt te herinneren.

Daarom kunnen twee mensen dezelfde gebeurtenis anders onthouden. Ze hoeven niet te liegen. Zelfs als je heel zeker bent van een detail, kan dat detail toch niet kloppen. Je geheugen is handig, maar geen perfecte opname.',extra_fact='Een vraag kan je herinnering sturen. Daarom zijn vragen zonder een voorgesteld antwoord belangrijk.',why_it_matters='Bij een verschil van mening kan het helpen om te weten dat herinneringen kunnen veranderen.' where slug='geheugen-reconstructie';
update public.me_knowledge_articles set title='Maak een gewoonte vast aan je dag',intro='Iets nieuws doen lukt vaak makkelijker na een vast moment.',body='Wil je vaker wandelen? Spreek met jezelf af: na de lunch loop ik tien minuten. Je lunch is dan het vaste startpunt. Je hoeft niet elke dag opnieuw te bedenken wanneer je gaat.

Begin klein. Vijf minuten bewegen is makkelijker om mee te starten dan een uur sporten. Maak het jezelf ook makkelijk: leg je schoenen bij de deur of je boek op je kussen. Zo valt je nieuwe gewoonte vanzelf meer op.',extra_fact='Een vast moment, zoals na de lunch, werkt ook als je niet iedere dag op dezelfde tijd eet.',why_it_matters='Een handige routine helpt je ook op dagen dat je weinig zin hebt.' where slug='gewoonte-anker';
update public.me_knowledge_articles set title='Hoe weet je telefoon waar je bent?',intro='GPS gebruikt signalen van satellieten om je plek te berekenen.',body='Een satelliet stuurt zijn plek en de verzendtijd van een signaal door. Je telefoon kijkt hoe lang het signaal onderweg was. Daarmee berekent hij de afstand tot de satelliet.

Eén afstand is niet genoeg. Met meerdere satellieten kan je telefoon bepalen waar je bent. Meestal zijn minstens vier nodig: voor je plek in drie richtingen én om een kleine fout in de klok van je telefoon te corrigeren. Hoge gebouwen kunnen de signalen verstoren.',extra_fact='Je telefoon gebruikt vaak ook wifi en mobiele netwerken om je plek sneller te vinden.',why_it_matters='Het blauwe bolletje op je kaart is het resultaat van heel precies tijd meten.' where slug='gps-positioning';
update public.me_knowledge_articles set title='Wat betekent inflatie?',intro='Bij inflatie worden dingen gemiddeld duurder.',body='Om inflatie te meten, kijken onderzoekers naar een pakket producten en diensten. Denk aan eten, energie en vervoer. Niet alles wordt evenveel duurder. Sommige dingen kunnen zelfs goedkoper worden.

Daalt de inflatie van acht naar drie procent? Dan stijgen de prijzen gemiddeld nog steeds, maar minder snel. Ze gaan dus niet vanzelf terug naar het oude bedrag. Hoeveel jij ervan merkt, hangt af van waar je geld aan uitgeeft.',extra_fact='Een verandering in energieprijzen kan veel invloed hebben op de kosten van een huishouden.',why_it_matters='Lagere inflatie betekent meestal een kleinere prijsstijging, niet lagere prijzen.' where slug='inflatie-kern';
update public.me_knowledge_articles set title='Waarom heeft een octopus drie harten?',intro='Twee harten helpen bij het opnemen van zuurstof. Het derde helpt de rest van het lichaam.',body='Een octopus haalt zuurstof uit water met zijn kieuwen. Twee harten pompen bloed door die kieuwen. Het bloed neemt daar zuurstof op. Het derde hart pompt dat bloed door het lichaam.

Het bloed ziet er blauwachtig uit. Dat komt door een stof met koper die zuurstof vervoert. Bij mensen gebruikt het bloed daarvoor een andere stof, met ijzer.',extra_fact='Bij sommige octopussen vertraagt of stopt het centrale hart tijdens actief zwemmen.',why_it_matters='Dieren kunnen op heel verschillende manieren zuurstof door hun lichaam vervoeren.' where slug='octopus-harten';
update public.me_knowledge_articles set title='Waarom is de nacht donker?',intro='Er zijn ontzettend veel sterren. Waarom maken ze de hele hemel dan niet licht?',body='Het heelal bestaat niet al oneindig lang. Licht van sommige verre plekken heeft nog niet genoeg tijd gehad om ons te bereiken. We zien dus niet zomaar alle sterren die er zijn.

Ook wordt het heelal groter. Daardoor wordt licht onderweg uitgerekt. Een deel verandert in licht dat onze ogen niet kunnen zien. Samen helpt dit verklaren waarom de nacht donker is.',extra_fact='Deze vraag staat bekend als de paradox van Olbers.',why_it_matters='Zelfs een donkere hemel vertelt iets over de geschiedenis van het heelal.' where slug='olbers-paradox-dark-night';
update public.me_knowledge_articles set title='Waarom stellen we dingen uit?',intro='Soms ontwijk je vooral het vervelende gevoel bij een taak.',body='Een taak kan saai, moeilijk of spannend voelen. Iets anders doen geeft dan even rust. Maar de taak blijft liggen. Een strengere planning lost dat gevoel niet altijd op.

Maak je eerste stap klein: open je document en schrijf drie zinnen. Of spreek af dat je tien minuten begint. Dat voelt minder zwaar dan een hele taak afmaken. Na het starten wordt doorgaan vaak makkelijker.',extra_fact='Zin om iets te doen ontstaat soms pas nadat je bent begonnen.',why_it_matters='Een kleine start helpt vaak meer dan boos worden op jezelf.' where slug='procrastination-emotion';
update public.me_knowledge_articles set title='Waarom werkt een beschadigde QR-code soms nog?',intro='Een QR-code bevat extra informatie als reserve.',body='De zwarte en witte vakjes bevatten gegevens. Er zit ook extra informatie in om ontbrekende stukjes te kunnen herstellen. Dat heet foutcorrectie. Daardoor kan een scanner soms een code lezen waar een kras of een klein logo overheen staat.

Het werkt niet bij elke beschadiging. De plek van de schade en de kwaliteit van de foto maken verschil. De drie grote vierkanten helpen de scanner zien waar de code staat en hoe hij is gedraaid.',extra_fact='Extra informatie maakt ook andere digitale systemen beter bestand tegen fouten.',why_it_matters='Een slim ontwerp houdt er rekening mee dat er iets mis kan gaan.' where slug='qr-foutcorrectie';
update public.me_knowledge_articles set title='Waarom staat Romeins beton er nog?',intro='Sommige Romeinse bouwwerken houden het al bijna tweeduizend jaar vol.',body='De Romeinen gebruikten verschillende betonmengsels. Vaak zat er kalk en vulkanische as in. Water kan met delen van zo’n mengsel reageren. Daarbij kan nieuw materiaal ontstaan dat kleine scheuren deels opvult.

Dat betekent niet dat elke scheur vanzelf verdwijnt. Ook is oud beton niet voor elke moderne klus beter. We bouwen nu vaak sneller en gebruiken bijvoorbeeld staal in beton. Onderzoekers bekijken wel wat we van de oude mengsels kunnen leren.',extra_fact='De koepel van het Pantheon in Rome is gemaakt van beton zonder stalen wapening.',why_it_matters='Oude bouwkennis kan helpen om materialen te maken die langer meegaan.' where slug='rome-beton';
update public.me_knowledge_articles set title='Slapen helpt je onthouden',intro='Je brein werkt tijdens je slaap verder met wat je hebt geleerd.',body='Een nieuwe herinnering is eerst nog kwetsbaar. Tijdens je slaap kan je brein die sterker maken en verbinden met wat je al weet. Dat heet consolidatie.

Slaap helpt ook om de volgende dag beter op te letten. Een nacht doorleren kan daarom tegenwerken. Je mist rust én tijd om het geleerde te verwerken. Oefenen op verschillende dagen en voldoende slapen gaan goed samen.',extra_fact='Slapen vervangt het oefenen niet. Zelf antwoorden proberen te onthouden blijft belangrijk.',why_it_matters='Plan bij het leren ook tijd voor slaap in.' where slug='slaap-geheugen';
update public.me_knowledge_articles set title='Hoe walvissen het zeeleven helpen',intro='Walvissen verplaatsen voedingsstoffen door de zee.',body='Walvissen eten soms diep in het water en poepen dichter bij het oppervlak. Zo komen voedingsstoffen op een andere plek terecht. Kleine organismen, zoals algen in plankton, kunnen die gebruiken om te groeien.

Algen nemen met behulp van zonlicht CO₂ op. Als materiaal naar diep water zinkt, kan een deel van die koolstof daar langere tijd blijven. Hoe groot de invloed van walvissen op het klimaat is, verschilt per gebied en is lastig te meten.',extra_fact='Plankton is voedsel voor veel dieren in zee.',why_it_matters='Eén diersoort kan ook invloed hebben op veel andere delen van de natuur.' where slug='whales-carbon-cycle';
update public.me_knowledge_articles set title='Waarom heeft rente zoveel invloed?',intro='Rente is onder andere de prijs die je betaalt om geld te lenen.',body='Als de rente stijgt, wordt een nieuwe lening vaak duurder. Een bedrijf kan dan besluiten om een nieuwe fabriek nog niet te bouwen. Die kost met een duurdere lening misschien te veel. Ook mensen die een huis willen kopen, kunnen de verandering merken.

Niet iedereen merkt het tegelijk. Bij sommige leningen staat de rente nog jaren vast. Daardoor kost het tijd voordat een renteverandering overal effect heeft.',extra_fact='Rente speelt ook een rol bij de keuze tussen sparen en geld investeren.',why_it_matters='De kosten van lenen verbinden onderwerpen als woningen, bedrijven en sparen met elkaar.' where slug='why-interest-rates-matter';
update public.me_knowledge_articles set title='Zonlicht is acht minuten onderweg',intro='Het licht op je gezicht vertrok ongeveer acht minuten geleden van de zon.',body='Licht reist ongeveer 300.000 kilometer per seconde. Dat is heel snel. Toch is de zon zo ver weg dat het licht ruim acht minuten nodig heeft om de aarde te bereiken.

Licht van andere sterren is nog veel langer onderweg. Als je naar een verre ster kijkt, zie je dus hoe die er vroeger uitzag. Soms kijk je honderden of duizenden jaren terug.',extra_fact='Een lichtjaar is de afstand die licht in één jaar aflegt. Het is dus geen tijdsduur.',why_it_matters='Hoe verder iets in het heelal wegstaat, hoe ouder het beeld is dat je ziet.' where slug='zonlicht-acht-minuten';
update public.me_knowledge_questions set question='Wat krijgen wortelschimmels van planten in ruil voor water en voedingsstoffen?',options='["Zuurstofrijke bloedcellen", "Suikers die de plant met zonlicht maakt", "Kleine stukjes boomschors", "Warmte uit de boomstam"]'::jsonb,explanation='Planten leveren suikers uit fotosynthese. De schimmeldraden helpen water en mineralen te bereiken.' where article_id=(select id from public.me_knowledge_articles where slug='bomen-netwerk');
update public.me_knowledge_questions set question='Waarom groeiden veel oude steden bij rivieren en kruispunten van handelsroutes?',options='["Omdat daar nooit overstromingen voorkwamen", "Omdat landbouw daar overbodig was", "Omdat alle handelaren er dezelfde taal spraken", "Omdat spullen en mensen er makkelijk konden samenkomen"]'::jsonb,explanation='Goede verbindingen maakten transport, handel, opslag en ambachten aantrekkelijk.' where article_id=(select id from public.me_knowledge_articles where slug='cities-and-trade');
update public.me_knowledge_questions set question='Waarom gingen plaatsen over van lokale zonnetijd naar standaardtijd?',options='["Om treintijden en berichten tussen plaatsen op elkaar af te stemmen", "Omdat de zon overal tegelijk opkwam", "Omdat alle landen één regering kregen", "Om de lengte van een dag te veranderen"]'::jsonb,explanation='Dienstregelingen en snelle communicatie maakten veel verschillende lokale tijden onpraktisch.' where article_id=(select id from public.me_knowledge_articles where slug='culturele-tijdzones');
update public.me_knowledge_questions set question='Waarom is je geheugen geen perfecte opname?',options='["Elke herinnering blijft een exacte video", "Alleen emoties worden opgeslagen", "Herinneringen worden opnieuw samengesteld en kunnen veranderen", "Zelfvertrouwen bewijst dat een herinnering klopt"]'::jsonb,explanation='Je brein combineert beelden, emoties, kennis en verwachtingen opnieuw. Nieuwe informatie kan herinneringen beïnvloeden.' where article_id=(select id from public.me_knowledge_articles where slug='geheugen-reconstructie');
update public.me_knowledge_questions set question='Wat is een bruikbaar anker voor een nieuwe gewoonte?',options='["Wachten op veel motivatie", "Nieuw gedrag koppelen aan iets dat al vanzelf gebeurt", "Meteen de zwaarste versie van het gedrag kiezen", "Iedere dag een ander startmoment zoeken"]'::jsonb,explanation='Een bestaand moment, zoals na de lunch, vermindert de dagelijkse beslissing over wanneer je begint.' where article_id=(select id from public.me_knowledge_articles where slug='gewoonte-anker');
update public.me_knowledge_questions set question='Waarom zijn in de praktijk minstens vier GPS-satellieten nuttig?',options='["Elke satelliet bestuurt één app", "De vierde satelliet maakt de kaartfoto", "Vier signalen zijn nodig om wifi aan te zetten", "Je telefoon berekent zijn plek in drie richtingen én een klokfout"]'::jsonb,explanation='Naast drie ruimtelijke coördinaten moet het toestel de kleine afwijking van zijn eigen klok oplossen.' where article_id=(select id from public.me_knowledge_articles where slug='gps-positioning');
update public.me_knowledge_questions set question='Wat betekent het meestal als inflatie van acht naar drie procent daalt?',options='["Het gemiddelde prijsniveau stijgt nog, maar langzamer", "Alle prijzen gaan terug naar hun oude niveau", "Elk product wordt vijf procent goedkoper", "Huishoudens ervaren voortaan dezelfde prijzen"]'::jsonb,explanation='Lagere positieve inflatie betekent een tragere prijsstijging. Het is niet hetzelfde als een dalend prijsniveau.' where article_id=(select id from public.me_knowledge_articles where slug='inflatie-kern');
update public.me_knowledge_questions set question='Welke taak hebben de twee kieuw-harten van een octopus?',options='["Ze maken het bloed rood", "Ze sturen bloed rechtstreeks naar alle armen", "Ze pompen bloed door de kieuwen voor zuurstofopname", "Ze vervangen de kieuwen tijdens zwemmen"]'::jsonb,explanation='De twee kieuw-harten sturen bloed door de kieuwen. Het centrale hart pompt het zuurstofrijke bloed door het lichaam.' where article_id=(select id from public.me_knowledge_articles where slug='octopus-harten');
update public.me_knowledge_questions set question='Welke combinatie helpt verklaren waarom de nachtelijke hemel donker is?',options='["Alle sterren doven tegelijk en de aarde staat stil", "Het heelal heeft een eindige leeftijd en dijt uit", "Het heelal is oneindig oud en krimpt", "Sterren geven uitsluitend onzichtbaar licht"]'::jsonb,explanation='Niet al het verre licht heeft ons bereikt. Door uitdijing wordt licht ook naar langere golflengten uitgerekt.' where article_id=(select id from public.me_knowledge_articles where slug='olbers-paradox-dark-night');
update public.me_knowledge_questions set question='Waarom kan een heel kleine eerste stap helpen tegen uitstellen?',options='["Omdat plannen dan overbodig is", "Omdat de hele taak vanzelf verdwijnt", "Omdat je eerst maximale motivatie nodig hebt", "Omdat beginnen dan minder zwaar voelt"]'::jsonb,explanation='Een kleine, concrete start maakt een onzekere of onaangename taak minder overweldigend.' where article_id=(select id from public.me_knowledge_articles where slug='procrastination-emotion');
update public.me_knowledge_questions set question='Hoe kan een scanner beschadigde informatie in een QR-code herstellen?',options='["Met extra informatie in de code", "Door altijd het origineel van internet te downloaden", "Door de drie grote vierkanten als tekst te lezen", "Door ontbrekende vakjes willekeurig in te vullen"]'::jsonb,explanation='Foutcorrectie gebruikt extra informatie om ontbrekende gegevens terug te rekenen. Niet iedere soort schade is herstelbaar.' where article_id=(select id from public.me_knowledge_articles where slug='qr-foutcorrectie');
update public.me_knowledge_questions set question='Waardoor kunnen sommige kleine scheuren in Romeins beton gedeeltelijk worden gevuld?',options='["Stalen wapening groeit voortdurend aan", "Elke scheur verdwijnt door zonlicht", "Water reageert met kalkrijke delen en vormt nieuw materiaal", "Romeins beton heeft nooit poriën"]'::jsonb,explanation='Water kan reacties met kalkrijke deeltjes op gang brengen. Nieuw materiaal kan een kleine opening gedeeltelijk vullen.' where article_id=(select id from public.me_knowledge_articles where slug='rome-beton');
update public.me_knowledge_questions set question='Hoe heet het proces waarbij nieuwe herinneringen tijdens slaap stabieler worden?',options='["Foutcorrectie", "Consolidatie", "Fotosynthese", "Inflatie"]'::jsonb,explanation='Consolidatie maakt herinneringen sterker en verbindt ze met wat je al weet.' where article_id=(select id from public.me_knowledge_articles where slug='slaap-geheugen');
update public.me_knowledge_questions set question='Hoe kunnen walvissen indirect de groei van plankton ondersteunen?',options='["Door het zonlicht tegen te houden", "Door alle koolstof uit zeewater te verwijderen", "Door voedingsstoffen op één diepte vast te houden", "Door voedingsstoffen tussen waterlagen te verplaatsen"]'::jsonb,explanation='Walvissen eten en scheiden afvalstoffen vaak op verschillende diepten uit. Daardoor komen voedingsstoffen beschikbaar voor plankton.' where article_id=(select id from public.me_knowledge_articles where slug='whales-carbon-cycle');
update public.me_knowledge_questions set question='Waarom kan een bedrijf een investering uitstellen wanneer rente stijgt?',options='["Een duurdere lening kan het project te duur maken", "Bestaande leningen verdwijnen dan", "Hogere rente maakt investeringen altijd winstgevender", "Rente beïnvloedt alleen spaargeld"]'::jsonb,explanation='Bij duurder krediet kan een project te weinig opleveren ten opzichte van de financieringskosten.' where article_id=(select id from public.me_knowledge_articles where slug='why-interest-rates-matter');
update public.me_knowledge_questions set question='Wat is een lichtjaar?',options='["De omlooptijd van de aarde rond de zon", "De helderheid van een ster gedurende een jaar", "De afstand die licht in één jaar aflegt", "De leeftijd van het zonlicht dat vandaag aankomt"]'::jsonb,explanation='Een lichtjaar is een afstandseenheid. Hoe verder een object wegstaat, hoe langer zijn licht onderweg is.' where article_id=(select id from public.me_knowledge_articles where slug='zonlicht-acht-minuten');
update public.me_read_sessions set min_seconds=public.me_article_seconds(article_id),active_seconds=least(active_seconds,public.me_article_seconds(article_id)) where completed_at is null;
commit;
